input_dir: /home/laurits/tauLifeTime_removeConst/  # Remove all weird constants when calculation lifetimes
# input_dir: /home/laurits/tauLifeTime_nosmear2/  # No vertex smearing (by Joosep)
# input_dir: /home/laurits/tauLifeTime_SiTracks_1  # Use SiTracks_1 instead of SiTracks_Refitted_1
# output_dir: /home/laurits/tauLifeTime_removeConst/plots
