max_num_files: 10
batch_size: 512
num_dataloader_workers: 0
classweight_sig: 1
classweight_bgr: 10
use_class_weights: True
use_per_jet_weights: True
use_focal_loss: True
focal_loss_gamma: 2.0
min_lr: 1.0e-6
max_lr: 1.0e0
verbosity: 1
