train_files: config/datasets/train.yaml
validation_files: config/datasets/validation.yaml
epochs: 500
batch_size: 512
lr: 0.0001
outpath: /home/tolange/CLIC_paper/ml-tau-reco/twostep_gpu/gnn_complete
runName: gnn_complete
extras: none
maxTrainFiles: -1
maxValFiles: -1
